version: '3'

services:
  docs:
    image: ride_app_back_local_docs
    container_name: ride_app_back_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ride_app_back:/app/ride_app_back:z
    ports:
      - '9000:9000'
    command: /start-docs
